/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("PurchaseRequestsListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onThePurchaseRequestsList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onThePurchaseRequestsList.onFilterBar().iCheckFilterField("status");
            Then.onThePurchaseRequestsList.onFilterBar().iCheckFilterField("requestDate");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onThePurchaseRequestsList.onTable().iCheckColumns(undefined, {"requestedBy":{"header":"Requested By"},"vendor/name":{"header":"Vendor"},"product/name":{"header":"Product"},"quantity":{"header":"Qty"},"totalAmount":{"header":"Total Amount"},"status":{"header":"Status"},"requestDate":{"header":"Request Date"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onThePurchaseRequestsList.onFilterBar().iExecuteSearch();
            
            Then.onThePurchaseRequestsList.onTable().iCheckRows();

            When.onThePurchaseRequestsList.onTable().iPressRow(0);
            Then.onThePurchaseRequestsObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});