/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("PurchaseRequestsObjectPageObjectPage journey");

        opaTest("Navigate to PurchaseRequestsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onThePurchaseRequestsList.onFilterBar().iExecuteSearch();

            Then.onThePurchaseRequestsList.onTable().iCheckRows();
            When.onThePurchaseRequestsList.onTable().iPressRow(0);

            Then.onThePurchaseRequestsObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onThePurchaseRequestsObjectPage.iCheckNumberOfSections(2);
            When.onThePurchaseRequestsObjectPage.iPressSectionIconTabFilterButton("FieldGroup::General");
            Then.onThePurchaseRequestsObjectPage.iCheckSection({ section: "FieldGroup::General" });
            Then.onThePurchaseRequestsObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "requestedBy" });
            Then.onThePurchaseRequestsObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "requestDate" });
            Then.onThePurchaseRequestsObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "status" });
            When.onThePurchaseRequestsObjectPage.iPressSectionIconTabFilterButton("FieldGroup::Details");
            Then.onThePurchaseRequestsObjectPage.iCheckSection({ section: "FieldGroup::Details" });
            Then.onThePurchaseRequestsObjectPage.onForm({ section: "FieldGroup::Details" }).iCheckField({ property: "vendor/name" });
            Then.onThePurchaseRequestsObjectPage.onForm({ section: "FieldGroup::Details" }).iCheckField({ property: "product/name" });
            Then.onThePurchaseRequestsObjectPage.onForm({ section: "FieldGroup::Details" }).iCheckField({ property: "quantity" });
            Then.onThePurchaseRequestsObjectPage.onForm({ section: "FieldGroup::Details" }).iCheckField({ property: "totalAmount" });
            Then.onThePurchaseRequestsObjectPage.onForm({ section: "FieldGroup::Details" }).iCheckField({ property: "notes" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});